server:
  port: 8081

spring:
  datasource:
    name: 127.0.0.1_mine
    url: jdbc:mysql://127.0.0.1:3306/mine?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: rootroot
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: classpath:/webapp/

mybatis:
  mapper-locations: classpath:mapper/**/**/*.xml
  type-aliases-package: com.kerwin.mine.**.**.domain
  type-handlers-package: com.kerwin.mine.**.**.dao
  configuration:
      map-underscore-to-camel-case: true
      default-fetch-size: 100
      default-statement-timeout: 30
